mapping/urls.py
from django.contrib import admin
from django.urls import path, include

from mapping import views
from mapping.views import *

app_name='mapping'
urlpatterns = [
    path('', MedimageLV.as_view(), name='index'),
    path('medimage/', MedimageLV.as_view(), name='medimage_list'),
    path('before/', BeforeLV.as_view(), name='medimage_before'),
    path('after/', AfterLV.as_view(), name='medimage_after'),
    path('add/', PostCreateView.as_view(), name='add'),
    path('medimage/<int:pk>', MedimageDV.as_view(), name='medimage_detail'),
]

mims/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mapping/', include('mapping.urls', namespace='mapping')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('member/', include('member.urls', namespace='member')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mapping/models.py
from __future__ import unicode_literals # Python 2.x 지원용
from django.utils.encoding import python_2_unicode_compatible
from django.utils.text import slugify

from django.conf import settings
from django.db import models
from django.urls import reverse

from mapping.fields import ThumbnailImageField

from django_unixdatetimefield import UnixDateTimeField

# Create your models here.

@python_2_unicode_compatible # Python 2.x 지원용
class Medimage(models.Model):
    requesterID = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    # request_time = models.DateTimeField('Request Date', auto_now_add=True)
    request_time = UnixDateTimeField('Request Date', auto_now_add=True)
    shooting_time = models.DateTimeField('Shooting Date', auto_now=True)
    emr_file = models.FileField('EMR File', blank=True)
    dicom_jpg_file = ThumbnailImageField('PACS File', upload_to='dicom_jpg/%Y/%m')
    pacs_file = models.FileField('PACS File', blank=True)
    progress = models.IntegerField('Viewing Progress')
    examination_name = models.CharField('Examination Name', max_length=50)
    examination_type = models.CharField('Examination Type', max_length=50)
    examination_site = models.CharField('Examination Site', max_length=50, blank=True)
    examination_regnum = models.IntegerField('Examination Register Number', unique=True)
    patient_id = models.CharField('Patient ID', max_length=50)

    def __str__(self):
        return self.examination_name
    
    def get_absolute_url(self):
        return reverse('mapping:medimage_detail', args=(self.id,))
    
    # def get_previous_post(self):
    #     return self.get_previous_by_modify_date()
    
    # def get_next_post(self):
    #     return self.get_next_by_modify_date()
        
    def save(self, *args, **kwargs):
        super(Medimage, self).save(*args, **kwargs)

mapping/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, get_list_or_404, render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView

from django.urls import reverse, reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin

from mapping.models import *

import requests, json

class MedimageLV(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    model = Medimage
    template_name = 'mapping/medimage_all.html'
    context_object_name = 'medimages'

class BeforeLV(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    template_name = 'mapping/medimage_before.html'
    context_object_name = 'medimages'
    paginate_by = 7

    def get_queryset(self, *args, **kwargs):
        return Medimage.objects.filter(requesterID=self.request.user, progress=0)

class AfterLV(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    model = Medimage
    template_name = 'mapping/medimage_after.html'
    context_object_name = 'medimages'
    paginate_by = 7

    def get_queryset(self, *args, **kwargs):
        return Medimage.objects.filter(requesterID=self.request.user, progress=1)

class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    model = Medimage
    template_name = 'mapping/medimage_form.html'
    fields = ['emr_file', 'dicom_jpg_file', 'pacs_file',
              'progress',
              'examination_name', 'examination_type',
              'examination_site', 'examination_regnum',
              'patient_id']
    # initial = {'slug': 'auto-filling-by-title'}
    success_url = reverse_lazy('mapping:index')
    
    def form_valid(self, form):  # self.request
        form.instance.owner = self.request.user
        form.instance.requesterID = self.request.user
        return super(PostCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PostCreateView, self).get_context_data(**kwargs)
        context['userid'] = self.request.user.id
        return context

class MedimageDV(LoginRequiredMixin, DetailView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    model = Medimage
    template_name = 'mapping/medimage_detail.html'
    context_object_name = 'medimages'

    def render_to_response(self, context, **response_kwargs):
        context = {}
        medimage = None
        medimage_pk = self.kwargs['pk']

        try:
            medimage = Medimage.objects.get(pk=medimage_pk)
        except Medimage.DoesNotExist:
            print('objects.get DoesNotExist')
        except:
            print('objects.get except')

        try:
            url = "http://59.29.224.87:8000/get_tuna/"+str(medimage_pk)
            result = requests.get(url)
            context['medimage_opinion'] = json.loads(result.text)['opinion']
            context['medimages'] = medimage
            print(json.loads(requests.get(url).text)['opinion'])
        except ConnectionError:
            context['medimage_opinion'] = "서버 연결 실패"
            context['medimages'] = medimage
        except ValueError:
            print('ValueError')
            context['medimage_opinion'] = "현재 소견 없음"
            context['medimages'] = medimage
        except:
            print('other except')
            context['medimage_opinion'] = "서버 연결 실패"
            context['medimages'] = medimage

        return self.response_class(
        request = self.request,
        template = self.get_template_names(),
        context = context,
        **response_kwargs
        )

mapping/templates/mapping/medimage_after.html
<!DOCTYPE html>

<html>

<head>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('.thumbnail_view').on('click', function (event) {
                event.preventDefault();
                console.log($(this).attr('id'));
                top.document.location.href = $(this).attr('id');
            });
        });
    </script>
</head>

<body>
    {% for medimage in medimages %}
    <div style="display:inline-block" id="{{ medimage.get_absolute_url }}" class="thumbnail_view">
            <div><img src="{{ medimage.dicom_jpg_file.thumb_url }}" alt="not"></div>
            <div>{{ medimage.requesterID }}</div>
            <div id="time">{{ medimage.request_time }}</div>
            <div>{{ medimage.dicom_jpg_file }}</div>
            <div>{{ medimage.progress }}</div>
            <div>{{ medimage.patient_id }}</div>
        </div>
    {% endfor %}

    <div>
            <span>
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">이전페이지</a>
                {% endif %}
    
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">다음페이지</a>
                {% endif %}
            </span>
        </div>
</body>

</html>

mapping/templates/mapping/medimage_all.html
{% extends "base.html" %}

{%block title %}Medimage List{% endblock %}

{% block content %}

<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
        $("#uploadBtn").on('click', function () {
            location.href = "{% url 'mapping:add' %}";
        });
    });
</script>

<div>
    <div style="background-color: aquamarine;" id="uploadBtn">업로드</div>
    <br>
    <div>
        <div style="background-color: aquamarine;">
            판독대기목록
        </div>
        <div>
            <object style="background-color: aquamarine;" width="100%" height="410" data="{% url 'mapping:medimage_before' %}"
                type="text/html"></object>
        </div>
    </div>
    <br>
    <div>
        <div style="background-color: aquamarine;">
            판독대기목록
        </div>
        <div>
            <object style="background-color: aquamarine;" width="100%" height="410" data="{% url 'mapping:medimage_after' %}"
                type="text/html"></object>
        </div>
    </div>
</div>

{% endblock %}

mapping/templates/mapping/medimage_before.html
<!DOCTYPE html>

<html>

<head>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('.thumbnail_view').on('click', function (event) {
                event.preventDefault();
                console.log($(this).attr('id'));
                top.document.location.href = $(this).attr('id');
            });
        });
    </script>
</head>

<body>
    {% for medimage in medimages %}
    <div style="display:inline-block" id="{{ medimage.get_absolute_url }}" class="thumbnail_view">
        <div><img src="{{ medimage.dicom_jpg_file.thumb_url }}" alt="not"></div>
        <div>{{ medimage.requesterID }}</div>
        <div id="time">{{ medimage.request_time }}</div>
        <div>{{ medimage.dicom_jpg_file }}</div>
        <div>{{ medimage.progress }}</div>
        <div>{{ medimage.patient_id }}</div>
    </div>
    {% endfor %}

    <div>
        <span>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">이전페이지</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">다음페이지</a>
            {% endif %}
        </span>
    </div>
</body>

</html>

mapping/templates/mapping/medimage_detail.html
{% extends "base.html" %}

{%block title %}Medimage Detail{% endblock %}

{% block content %}

<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
        // $.ajax({
        //     type: "GET", // 데이터를 전송하는 방법을 지정
        //     url: "http://59.29.224.87:8000/get_tuna/{{ medimages.id }}", // 통신할 url을 지정
        //     dataType: "json",
        //     success: function (response) { // 통신 성공시
        //         console.log("ajax - GET success!", response);
        //         $("#div_opinion").hide();
        //         $("#recent_opinion").text(response.opinion);
        //     },
        //     error: function (request, status, error) { // 통신 실패시 - 로그인 페이지 리다이렉트
        //         if (status === "parsererror") {
        //             $("#recent_opinion").text("현재 소견 없음");
        //         } else {
        //             $("#recent_opinion").text("서버 연결 실패");
        //         }

        //         // alert("GET error test" + response)
        //         console.log(request.responseText);
        //         console.log("---------------");
        //         console.log(status);
        //         console.log("---------------");
        //         console.log(error);
        //         console.log("---------------");
        //     },
        // });
        $("#add_opinion").click(function () {
            opinion = $("#input_opinion").val();
            $.ajax({
                // contentType: "application/json; charset=UTF-8",
                type: "POST", // 데이터를 전송하는 방법을 지정
                url: "http://59.29.224.87:8000/add_opinion", // 통신할 url을 지정
                data: JSON.stringify({ 'id': '{{ medimages.id }}', 'opinion': opinion, 'csrfmiddlewaretoken': '{{ csrf_token }}' }), // 서버로 데이터 전송시 옵션
                dataType: "json",
                success: function (response) { // 통신 성공시
                    alert("ajax - POST success!");
                    console.log("success!", response);
                    $("#recent_opinion").text(JSON.stringify(response));
                },
                error: function (response) {
                    console.log("error!", response);
                }
            });
        });
    });
</script>

<div style="background-color: aquamarine;">
    <p>현재 소견</p>
    {% if medimage_opinion %}
    <p id="recent_opinion">{{ medimage_opinion }}</p>
    {% endif %}
</div>
<br>
<div style="background-color: aquamarine;" id="div_opinion">
    <p>소견 입력</p>
    <input type="text" id="input_opinion">
    <input type="button" value="소견 전송" id="add_opinion">
</div>
<br>
<div style="background-color: aquamarine;">
    {% if medimages %}
    <img src="{{ medimages.dicom_jpg_file.origin_url }}" alt="" heigth="50%" width="50%">
    {% endif %}
</div>

{% endblock %}

mapping/templates/mapping/medimage_form.html
{% extends "base.html" %}

{% block title %}Medimage 생성 페이지{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<h1>Medimage Create/Update - {{ medimage }} </h1>
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.errors %}
            {{ form.errors }}
        {% endif %}

        <p>등록(수정)하고 싶은 Medimage를 작성해 주세요.</p>
        <fieldset class="aligned">
            <div class="form-row">
                {{form.emr_file.label_tag}} {{form.emr_file}}
            </div>
            <div class="form-row">
                {{form.dicom_jpg_file.label_tag}} {{form.dicom_jpg_file}}
            </div>
            <div class="form-row">
                {{form.pacs_file.label_tag}} {{form.pacs_file}}
            </div>
            <div class="form-row">
                {{form.progress.label_tag}} {{form.progress}}
            </div>
            <div class="form-row">
                {{form.examination_name.label_tag}} {{form.examination_name}}
            </div>
            <div class="form-row">
                {{form.examination_type.label_tag}} {{form.examination_type}}
            </div>
            <div class="form-row">
                {{form.examination_site.label_tag}} {{form.examination_site}}
            </div>
            <div class="form-row">
                {{form.examination_regnum.label_tag}} {{form.examination_regnum}}
            </div>
            <div class="form-row">
                {{form.patient_id.label_tag}} {{form.patient_id}}
            </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="등록" />
        </div>
    </form>
{% endblock %}